-- lsc-pop star schema ({ref}; {variant} roll-forward, recorded in metadata). MODELLED ESTIMATES - NOT OFFICIAL STATISTICS.
-- Generated by lsc_pop.outputs (run {run_id}). Load the Parquet files (canonical); CSVs are equivalent.
-- Databricks example:  CREATE TABLE fact_population USING PARQUET LOCATION '<path>/fact_population.parquet';

CREATE TABLE fact_population (
  lsoa21cd        STRING   NOT NULL,  -- FK dim_lsoa
  sex             STRING   NOT NULL,  -- 'F' | 'M'
  age             SMALLINT NOT NULL,  -- 0..90 (90 = 90+); FK dim_age
  eth19           SMALLINT NOT NULL,  -- 1..19; FK dim_ethnicity
  population      DOUBLE   NOT NULL,  -- unrounded; sums to ONS mid-year per lsoa x sex x age
  reference_year  SMALLINT NOT NULL   -- e.g. 2024 (30 June); lets later mid-years be appended
);
-- dim_lsoa (1 row per LSOA 2021): geography (icb_cd, sicbl_cd, lad_cd, nhser_cd, msoa21cd, ltla21cd,
--   rgn21cd + names, nhs_geog_vintage), IoD 2025 (imd_score/rank/decile, domain scores/ranks/deciles),
--   imd_quintile, core20, imd_local_quintile, in_focus_icb, population_mid<year>.
-- dim_ethnicity (eth19 -> code_6/label_6, code_5/label_5), dim_age (age_5yr, age_10yr, census_band_rm032),
-- dim_trust (trust_code, trust_name, trust_type, is_focus; includes 'UNASSIGNED'),
-- bridge_lsoa_trust (lsoa21cd, msoa21cd, trust_code, proportion_published, proportion_rescaled, fptp).

-- 1. ICB x 6 ethnic groups x 5-year bands
SELECT l.icb_nm, e.label_6, a.age_5yr, a.age_5yr_sort, SUM(f.population) AS population
FROM fact_population f
JOIN dim_lsoa l USING (lsoa21cd)
JOIN dim_ethnicity e USING (eth19)
JOIN dim_age a USING (age)
GROUP BY l.icb_nm, e.label_6, a.age_5yr, a.age_5yr_sort
ORDER BY l.icb_nm, e.label_6, a.age_5yr_sort;

-- 2. Acute trust catchment population by ethnic group (published OHID shares; 'UNASSIGNED' holds
--    the suppressed remainder). Use proportion_rescaled for catchments that include everyone.
SELECT t.trust_name, e.label_6,
       SUM(f.population * b.proportion_published) AS catchment_published,
       SUM(f.population * b.proportion_rescaled)  AS catchment_rescaled
FROM fact_population f
JOIN bridge_lsoa_trust b USING (lsoa21cd)
JOIN dim_trust t USING (trust_code)
JOIN dim_ethnicity e USING (eth19)
WHERE t.is_focus
GROUP BY t.trust_name, e.label_6;

-- 3. L&SC population by within-ICB IMD quintile and ethnic group; Core20 share
SELECT l.imd_local_quintile, e.label_6, SUM(f.population) AS population
FROM fact_population f JOIN dim_lsoa l USING (lsoa21cd) JOIN dim_ethnicity e USING (eth19)
WHERE l.in_focus_icb
GROUP BY l.imd_local_quintile, e.label_6;
